name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: redkubes/docusaurus-deploy-action@master
        with:
          source-folder: .
          git-user: ornias1993
          git-password: ${{ secrets.GITHUB_TOKEN }}
          deployment-branch: gh-pages
